export default [
    {
        "id": "2",
        "title": "Galaxy S25 Ultra",
        "category": "Electronics",
        "image_url": "http://res.cloudinary.com/bunnur7c/image/upload/v1785064294/cqv8qfay64ttrvwiaakd.png",
        "brand": "Samsung",
        "ratings": 4.4,
        "rating_count": 1681,
        "price": 135000,
        "discounted_price": 115000,
        "discount_percentage": 15,
        "stock": 76,
        "estimated_delivery_time": "6 days",
        "is_featured": false,
        "search_tags": [
            "samsung",
            "galaxy",
            "s25 ultra",
            "samsung galaxy s25 ultra",
            "android",
            "smartphone",
            "mobile phone",
            "flagship phone",
            "electronics"
        ]
    },
    {
        "id": "3",
        "title": "Pixel 10 Pro",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSTClFKM3D6Vjg4tzxCqaJQm5TMG6BuCSVxRQ31e0b3xxPF_ruErG2S_1N&s=10",
        "brand": "Google",
        "ratings": 4.9,
        "rating_count": 5393,
        "price": 60598,
        "discounted_price": 44843,
        "discount_percentage": 26,
        "stock": 73,
        "estimated_delivery_time": "2 days",
        "is_featured": true,
        "search_tags": [
            "google",
            "pixel",
            "pixel 10 pro",
            "google pixel",
            "android",
            "smartphone",
            "mobile phone",
            "ai phone",
            "best camera phone",
            "electronics"
        ]
    },
    {
        "id": "4",
        "title": "MacBook Air M3",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-azO2ftpM5ff9smffUAcgwuCtP2JuoHIrmFXtf3Z0Ng&s=10",
        "brand": "Apple",
        "ratings": 4.5,
        "rating_count": 1190,
        "price": 55000,
        "discounted_price": 45000,
        "discount_percentage": 18,
        "stock": 113,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "apple",
            "macbook",
            "macbook air",
            "macbook air m3",
            "m3 chip",
            "laptop",
            "notebook",
            "macos",
            "thin laptop",
            "electronics"
        ]
    },
    {
        "id": "5",
        "title": "Inspiron 15",
        "category": "Electronics",
        "image_url": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/inspiron-notebooks/15-3535-amd/spi/plastic/black/ng/notebook-inspiron-15-3535-plastic-black-campaign-hero-504x350-ng.psd?fmt=jpg&wid=570&hei=400",
        "brand": "Dell",
        "ratings": 4.3,
        "rating_count": 1621,
        "price": 119325,
        "discounted_price": 106199,
        "discount_percentage": 11,
        "stock": 34,
        "estimated_delivery_time": "5 days",
        "is_featured": false,
        "search_tags": [
            "dell",
            "inspiron",
            "inspiron 15",
            "dell laptop",
            "laptop",
            "notebook",
            "windows laptop",
            "office laptop",
            "student laptop",
            "electronics"
        ]
    },
    {
        "id": "6",
        "title": "Legion 5",
        "category": "Electronics",
        "image_url": "https://m.media-amazon.com/images/I/81O1uCPS8lL.jpg",
        "brand": "Lenovo",
        "ratings": 4.8,
        "rating_count": 5290,
        "price": 113300,
        "discounted_price": 79310,
        "discount_percentage": 30,
        "stock": 49,
        "estimated_delivery_time": "3 days",
        "is_featured": true,
        "search_tags": [
            "lenovo",
            "legion",
            "legion 5",
            "gaming laptop",
            "laptop",
            "gaming pc",
            "rtx graphics",
            "lenovo gaming",
            "electronics"
        ]
    },
    {
        "id": "7",
        "title": "WH-1000XM5",
        "category": "Electronics",
        "image_url": "https://shopatsc.com/cdn/shop/products/2500x2500_Silver_1.jpg?v=1694415813",
        "brand": "Sony",
        "ratings": 4.5,
        "rating_count": 3968,
        "price": 39984,
        "discounted_price": 29588,
        "discount_percentage": 26,
        "stock": 116,
        "estimated_delivery_time": "3 days",
        "is_featured": false,
        "search_tags": [
            "sony",
            "wh-1000xm5",
            "xm5",
            "headphones",
            "noise cancelling",
            "wireless headphones",
            "bluetooth headphones",
            "audio",
            "anc",
            "electronics"
        ]
    },
    {
        "id": "8",
        "title": "AirPods Pro 2",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk55ZnFTc9iApVVN-Sc7pEicFqUefdYIa8kQ3_hmR56g&s=10",
        "brand": "Apple",
        "ratings": 4.5,
        "rating_count": 200,
        "price": 5233,
        "discounted_price": 4343,
        "discount_percentage": 17,
        "stock": 92,
        "estimated_delivery_time": "6 days",
        "is_featured": true,
        "search_tags": [
            "apple",
            "airpods",
            "airpods pro 2",
            "earbuds",
            "wireless earbuds",
            "bluetooth earphones",
            "audio",
            "anc",
            "tws",
            "electronics"
        ]
    },
    {
        "id": "9",
        "title": "Galaxy Tab S10",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStyRn7PUZQ71bEYae2Nf92OasPXl9dIuJD_DwzI4BWWQ&s=10",
        "brand": "Samsung",
        "ratings": 4.4,
        "rating_count": 1766,
        "price": 95880,
        "discounted_price": 81498,
        "discount_percentage": 15,
        "stock": 43,
        "estimated_delivery_time": "6 days",
        "is_featured": false,
        "search_tags": [
            "samsung",
            "galaxy tab",
            "tab s10",
            "tablet",
            "android tablet",
            "samsung tablet",
            "display",
            "electronics"
        ]
    },
    {
        "id": "10",
        "title": "iPad Air M3",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEnNfG0Wwp69u8XwgBHYrkFJfJyPjO6Sb1xlYcTzPe7Q&s=10",
        "brand": "Apple",
        "ratings": 4.9,
        "rating_count": 397,
        "price": 2319,
        "discounted_price": 1693,
        "discount_percentage": 27,
        "stock": 70,
        "estimated_delivery_time": "2 days",
        "is_featured": false,
        "search_tags": [
            "apple",
            "ipad",
            "ipad air",
            "ipad air m3",
            "tablet",
            "ios tablet",
            "m3 ipad",
            "apple pencil",
            "electronics"
        ]
    },
    {
        "id": "11",
        "title": "Surface Laptop 7",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbRX4P5ykLNYSaM2Hmn2sno_f3jEUzEZq5LAbvMXR1kQ&s=10",
        "brand": "Microsoft",
        "ratings": 4.7,
        "rating_count": 3234,
        "price": 69718,
        "discounted_price": 52288,
        "discount_percentage": 25,
        "stock": 116,
        "estimated_delivery_time": "7 days",
        "is_featured": true,
        "search_tags": [
            "microsoft",
            "surface",
            "surface laptop 7",
            "windows laptop",
            "laptop",
            "notebook",
            "touchscreen laptop",
            "ultrabook",
            "electronics"
        ]
    },
    {
        "id": "12",
        "title": "ROG Zephyrus G16",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtklIAGm-hBVndM08-o2sxvLlIBBCP4EMtaUvO3R1nhA&s=10",
        "brand": "ASUS",
        "ratings": 4.7,
        "rating_count": 3477,
        "price": 58415,
        "discounted_price": 44980,
        "discount_percentage": 23,
        "stock": 5,
        "estimated_delivery_time": "4 days",
        "is_featured": true,
        "search_tags": [
            "asus",
            "rog",
            "zephyrus",
            "gaming laptop",
            "rog zephyrus g16",
            "laptop",
            "gaming pc",
            "asus rog",
            "electronics"
        ]
    },
    {
        "id": "13",
        "title": "Onplus 10R",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9fSU50-rEBtBUpm15hWhxUqgvcqPaBpNalg3EYuUE3w&s",
        "brand": "OnePlus",
        "ratings": 4.9,
        "rating_count": 1226,
        "price": 95855,
        "discounted_price": 68057,
        "discount_percentage": 29,
        "stock": 87,
        "estimated_delivery_time": "4 days",
        "is_featured": false,
        "search_tags": [
            "oneplus",
            "oneplus 13",
            "smartphone",
            "mobile phone",
            "android",
            "flagship phone",
            "fast charging phone",
            "electronics"
        ]
    },
    {
        "id": "14",
        "title": "Moto Edge 60",
        "category": "Electronics",
        "image_url": "https://m.media-amazon.com/images/I/61NsPikkMBL.jpg",
        "brand": "Motorola",
        "ratings": 4.5,
        "rating_count": 253,
        "price": 42309,
        "discounted_price": 38501,
        "discount_percentage": 9,
        "stock": 47,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "motorola",
            "moto",
            "moto edge 60",
            "smartphone",
            "mobile phone",
            "android",
            "motorola edge",
            "electronics"
        ]
    },
    {
        "id": "15",
        "title": "GoPro HERO13",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLnzWs6hQvHbjZF3y8O8lBzY9MeHHjKreMcHSHRqP4kA&s=10",
        "brand": "GoPro",
        "ratings": 4.9,
        "rating_count": 2151,
        "price": 109642,
        "discounted_price": 80039,
        "discount_percentage": 27,
        "stock": 73,
        "estimated_delivery_time": "2 days",
        "is_featured": false,
        "search_tags": [
            "gopro",
            "hero13",
            "action camera",
            "gopro hero 13",
            "vlogging camera",
            "waterproof camera",
            "video camera",
            "electronics"
        ]
    },
    {
        "id": "16",
        "title": "Kindle Paperwhite",
        "category": "Electronics",
        "image_url": "https://cdn.cs.1worldsync.com/8c/c1/8cc1b6aa-1300-436d-98c3-71b044d3d78a.jpg",
        "brand": "Amazon",
        "ratings": 4.2,
        "rating_count": 1204,
        "price": 49026,
        "discounted_price": 38731,
        "discount_percentage": 21,
        "stock": 106,
        "estimated_delivery_time": "2 days",
        "is_featured": true,
        "search_tags": [
            "amazon",
            "kindle",
            "kindle paperwhite",
            "ereader",
            "ebook reader",
            "digital book",
            "tablet",
            "electronics"
        ]
    },
    {
        "id": "17",
        "title": "Apple Watch Series 10",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt-sX9xTzhQQWVD6IUvnee0vALhsWC1FWAlbaaVFmrog&s=10",
        "brand": "Apple",
        "ratings": 4.7,
        "rating_count": 460,
        "price": 41830,
        "discounted_price": 30954,
        "discount_percentage": 26,
        "stock": 21,
        "estimated_delivery_time": "7 days",
        "is_featured": true,
        "search_tags": [
            "apple",
            "apple watch",
            "series 10",
            "smartwatch",
            "fitness tracker",
            "wearable",
            "ios watch",
            "electronics"
        ]
    },
    {
        "id": "18",
        "title": "Galaxy Watch Ultra",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuPg_g_xxb2kVeMXDnqbT5rpgUMRkR2Ylw32FaW5ibDw&s=10",
        "brand": "Samsung",
        "ratings": 4.5,
        "rating_count": 4993,
        "price": 30882,
        "discounted_price": 25323,
        "discount_percentage": 18,
        "stock": 65,
        "estimated_delivery_time": "2 days",
        "is_featured": true,
        "search_tags": [
            "samsung",
            "galaxy watch",
            "watch ultra",
            "smartwatch",
            "fitness tracker",
            "wearable",
            "android watch",
            "electronics"
        ]
    },
    {
        "id": "19",
        "title": "Logitech MX Master 3S",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5BDkM0i6NLPXZ5Wszf3rhG_uxVoIXdF5l601GzZg3y3Hvj4Yzz2XsWp8&s=10",
        "brand": "Logitech",
        "ratings": 4.4,
        "rating_count": 3508,
        "price": 26506,
        "discounted_price": 22265,
        "discount_percentage": 16,
        "stock": 32,
        "estimated_delivery_time": "4 days",
        "is_featured": true,
        "search_tags": [
            "logitech",
            "mx master 3s",
            "wireless mouse",
            "mouse",
            "ergonomic mouse",
            "computer accessories",
            "mx master",
            "electronics"
        ]
    },
    {
        "id": "20",
        "title": "LG UltraGear 27",
        "category": "Electronics",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD9Zlqk_abxxRvrjczIugnSrLMVIeoLfTsL0JSo9MC4A&s=10",
        "brand": "LG",
        "ratings": 4.3,
        "rating_count": 1737,
        "price": 73119,
        "discounted_price": 60689,
        "discount_percentage": 17,
        "stock": 95,
        "estimated_delivery_time": "2 days",
        "is_featured": true,
        "search_tags": [
            "lg",
            "ultragear",
            "gaming monitor",
            "monitor",
            "display",
            "pc monitor",
            "27 inch monitor",
            "electronics"
        ]
    },
    {
        "id": "21",
        "title": "Slim Fit T-Shirt",
        "category": "Fashion",
        "image_url": "https://m.media-amazon.com/images/I/81-jakwvPyL._AC_UY1100_.jpg",
        "brand": "Levi's",
        "ratings": 4.9,
        "rating_count": 496,
        "price": 720,
        "discounted_price": 569,
        "discount_percentage": 21,
        "stock": 59,
        "estimated_delivery_time": "2 days",
        "is_featured": false,
        "search_tags": [
            "levis",
            "tshirt",
            "tee",
            "slim fit t-shirt",
            "men clothing",
            "casual wear",
            "fashion",
            "apparel"
        ]
    },
    {
        "id": "22",
        "title": "Classic Jeans",
        "category": "Fashion",
        "image_url": "https://pyxis.nymag.com/v1/imgs/58a/6b2/b09ab941a617c9c15d3aaf7be305b44dd5-denim-6-25-6.rsquare.w600.jpg",
        "brand": "Wrangler",
        "ratings": 4.2,
        "rating_count": 710,
        "price": 1857,
        "discounted_price": 1541,
        "discount_percentage": 17,
        "stock": 113,
        "estimated_delivery_time": "5 days",
        "is_featured": false,
        "search_tags": [
            "wrangler",
            "jeans",
            "denim",
            "classic jeans",
            "men jeans",
            "pants",
            "casual wear",
            "fashion",
            "apparel"
        ]
    },
    {
        "id": "23",
        "title": "Running Shoes",
        "category": "Fashion",
        "image_url": "https://m.media-amazon.com/images/I/81Y+8YHg3AL._AC_UY1000_.jpg",
        "brand": "Nike",
        "ratings": 4.5,
        "rating_count": 2585,
        "price": 4201,
        "discounted_price": 3781,
        "discount_percentage": 10,
        "stock": 60,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "nike",
            "running shoes",
            "sneakers",
            "sports shoes",
            "footwear",
            "jogging shoes",
            "nike shoes",
            "fashion"
        ]
    },
    {
        "id": "24",
        "title": "Hoodie",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNMBuzDARMsLc2xewb3mt_mldyxlEC0soj584GUWlGaRyYqoNLm7RWGBut&s=10",
        "brand": "Puma",
        "ratings": 4.9,
        "rating_count": 2337,
        "price": 2554,
        "discounted_price": 2018,
        "discount_percentage": 21,
        "stock": 104,
        "estimated_delivery_time": "6 days",
        "is_featured": true,
        "search_tags": [
            "puma",
            "hoodie",
            "sweatshirt",
            "winter wear",
            "sportswear",
            "puma hoodie",
            "casual wear",
            "fashion",
            "apparel"
        ]
    },
    {
        "id": "25",
        "title": "Formal Shirt",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcVf--l7Tbn4Xg6IcC3Om8qkNBYc92Wmo0xIpy5m-MfmzU7Pb4RCyNB_3b&s=10",
        "brand": "Allen Solly",
        "ratings": 4.3,
        "rating_count": 764,
        "price": 4986,
        "discounted_price": 3690,
        "discount_percentage": 26,
        "stock": 56,
        "estimated_delivery_time": "4 days",
        "is_featured": false,
        "search_tags": [
            "allen solly",
            "formal shirt",
            "dress shirt",
            "office wear",
            "men shirt",
            "button up shirt",
            "fashion",
            "apparel"
        ]
    },
    {
        "id": "26",
        "title": "Leather Wallet",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3U01J6lke1yUcyVrsJAvEqhUDnGe-mMVEnQMNT95ijw&s=10",
        "brand": "Tommy Hilfiger",
        "ratings": 4.8,
        "rating_count": 709,
        "price": 686,
        "discounted_price": 617,
        "discount_percentage": 10,
        "stock": 56,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "tommy hilfiger",
            "wallet",
            "leather wallet",
            "mens wallet",
            "purse",
            "accessories",
            "fashion"
        ]
    },
    {
        "id": "27",
        "title": "Backpack",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0J2RK4VqG9YeLZT7TdQAdK8jz-7SIHpbl-kGOUBFIKQ&s=10",
        "brand": "Wildcraft",
        "ratings": 4.4,
        "rating_count": 4993,
        "price": 1521,
        "discounted_price": 1308,
        "discount_percentage": 14,
        "stock": 67,
        "estimated_delivery_time": "5 days",
        "is_featured": false,
        "search_tags": [
            "wildcraft",
            "backpack",
            "bag",
            "school bag",
            "travel bag",
            "wildcraft bag",
            "accessories",
            "fashion"
        ]
    },
    {
        "id": "28",
        "title": "Sneakers",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtMNOKs60RoVGB3scfKLGeSp7HwTeNORfBpbjw6bF2drqsANJldfT1LsA&s=10",
        "brand": "Adidas",
        "ratings": 4.7,
        "rating_count": 3786,
        "price": 6765,
        "discounted_price": 5750,
        "discount_percentage": 15,
        "stock": 113,
        "estimated_delivery_time": "4 days",
        "is_featured": false,
        "search_tags": [
            "adidas",
            "sneakers",
            "shoes",
            "casual shoes",
            "footwear",
            "adidas shoes",
            "fashion"
        ]
    },
    {
        "id": "29",
        "title": "Analog Watch",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-vKKP9RyES9mwZSTRFNpOlkZPjVpufZBtm3G6QZiQJ1bNP4iqR2WCatA&s=10",
        "brand": "Fossil",
        "ratings": 4.4,
        "rating_count": 696,
        "price": 5795,
        "discounted_price": 4057,
        "discount_percentage": 30,
        "stock": 108,
        "estimated_delivery_time": "5 days",
        "is_featured": true,
        "search_tags": [
            "fossil",
            "watch",
            "analog watch",
            "fossil watch",
            "mens watch",
            "wrist watch",
            "accessories",
            "fashion"
        ]
    },
    {
        "id": "30",
        "title": "Denim Jacket",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKMKMyoTDdMdURu9BR-HJDo2355MG_mYbsA2v5QKiXMvP5MC21nvq6SamC&s=10",
        "brand": "Levi's",
        "ratings": 4.4,
        "rating_count": 3144,
        "price": 8455,
        "discounted_price": 6426,
        "discount_percentage": 24,
        "stock": 16,
        "estimated_delivery_time": "4 days",
        "is_featured": true,
        "search_tags": [
            "levis",
            "jacket",
            "denim jacket",
            "jeans jacket",
            "winter wear",
            "outerwear",
            "casual wear",
            "fashion",
            "apparel"
        ]
    },
    {
        "id": "31",
        "title": "Cargo Pants",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSQEkYqvNJs7X0PaLSlmw6MBP3uIEPYPZU3jBP8bvzNxFqxypCGfzxFNk&s=10",
        "brand": "U.S. Polo Assn.",
        "ratings": 4.7,
        "rating_count": 3429,
        "price": 5349,
        "discounted_price": 4493,
        "discount_percentage": 16,
        "stock": 37,
        "estimated_delivery_time": "4 days",
        "is_featured": false,
        "search_tags": [
            "us polo",
            "cargo pants",
            "cargos",
            "trousers",
            "men pants",
            "casual wear",
            "utility pants",
            "fashion",
            "apparel"
        ]
    },
    {
        "id": "32",
        "title": "Sunglasses",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO0rDMZU26-qXnuigUU6IQDLPGmLjbjTqxqQy8vr2NOlo5jwfX1_nq4_6t&s=10",
        "brand": "Ray-Ban",
        "ratings": 4.4,
        "rating_count": 3766,
        "price": 8708,
        "discounted_price": 7837,
        "discount_percentage": 10,
        "stock": 64,
        "estimated_delivery_time": "6 days",
        "is_featured": false,
        "search_tags": [
            "rayban",
            "sunglasses",
            "shades",
            "goggles",
            "ray-ban glasses",
            "eyewear",
            "accessories",
            "fashion"
        ]
    },
    {
        "id": "33",
        "title": "Polo T-Shirt",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2s4zlk-8rd4i8N6deFf-YnqXZdFP4wgD16DNgKYp162M7w5bkohoW7Qw&s=10",
        "brand": "Van Heusen",
        "ratings": 4.4,
        "rating_count": 2983,
        "price": 4175,
        "discounted_price": 3507,
        "discount_percentage": 16,
        "stock": 109,
        "estimated_delivery_time": "7 days",
        "is_featured": true,
        "search_tags": [
            "van heusen",
            "polo",
            "tshirt",
            "polo t-shirt",
            "collar shirt",
            "men clothing",
            "casual wear",
            "fashion",
            "apparel"
        ]
    },
    {
        "id": "34",
        "title": "Kurta",
        "category": "Fashion",
        "image_url": "https://imagescdn.tasva.com/img/app/product/1/1077388-16665192.jpg?w=500&auto=format",
        "brand": "Manyavar",
        "ratings": 4.7,
        "rating_count": 2789,
        "price": 5156,
        "discounted_price": 3970,
        "discount_percentage": 23,
        "stock": 91,
        "estimated_delivery_time": "2 days",
        "is_featured": false,
        "search_tags": [
            "manyavar",
            "kurta",
            "ethnic wear",
            "traditional wear",
            "festive wear",
            "men kurta",
            "wedding wear",
            "fashion",
            "apparel"
        ]
    },
    {
        "id": "35",
        "title": "Sports Cap",
        "category": "Fashion",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXH2ekRltsPVfhx-tn8OfxAkFzeJU0ogEcyX3cP_80RoKv6JS1Q0AE9yQ&s=10",
        "brand": "Nike",
        "ratings": 4.4,
        "rating_count": 5019,
        "price": 5982,
        "discounted_price": 4247,
        "discount_percentage": 29,
        "stock": 75,
        "estimated_delivery_time": "3 days",
        "is_featured": true,
        "search_tags": [
            "nike",
            "cap",
            "sports cap",
            "hat",
            "nike cap",
            "running cap",
            "accessories",
            "fashion"
        ]
    },
    {
        "id": "36",
        "title": "Hydrating Face Wash",
        "category": "Beauty",
        "image_url": "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T28122_150662.png",
        "brand": "SNISS",
        "ratings": 4.7,
        "rating_count": 3484,
        "price": 5022,
        "discounted_price": 4068,
        "discount_percentage": 19,
        "stock": 25,
        "estimated_delivery_time": "2 days",
        "is_featured": false,
        "search_tags": [
            "cetaphil",
            "face wash",
            "cleanser",
            "hydrating face wash",
            "skincare",
            "sensitive skin",
            "dry skin",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "37",
        "title": "Vitamin C Serum",
        "category": "Beauty",
        "image_url": "https://www.thenaturalwash.com/cdn/shop/files/vitamin_c_serum_1.jpg?v=1769665589",
        "brand": "Minimalist",
        "ratings": 4.6,
        "rating_count": 2662,
        "price": 1497,
        "discounted_price": 1198,
        "discount_percentage": 20,
        "stock": 110,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "minimalist",
            "serum",
            "vitamin c serum",
            "skincare",
            "glow serum",
            "face serum",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "38",
        "title": "Matte Lipstick",
        "category": "Beauty",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDrGl1WXO4CDMHmo97ul7KrMLY48bVcDF1Zy5hUB-9ng&s=10",
        "brand": "Maybelline",
        "ratings": 4.6,
        "rating_count": 2295,
        "price": 8722,
        "discounted_price": 7763,
        "discount_percentage": 11,
        "stock": 36,
        "estimated_delivery_time": "6 days",
        "is_featured": false,
        "search_tags": [
            "maybelline",
            "lipstick",
            "matte lipstick",
            "makeup",
            "lip color",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "39",
        "title": "Moisturizer",
        "category": "Beauty",
        "image_url": "https://www.thenaturalwash.com/cdn/shop/products/Face_Moisturizing_Cream_for_Dry_to_Combination_Skin.jpg?v=1754560927",
        "brand": "CeraVe",
        "ratings": 4.4,
        "rating_count": 2403,
        "price": 953,
        "discounted_price": 781,
        "discount_percentage": 18,
        "stock": 92,
        "estimated_delivery_time": "7 days",
        "is_featured": true,
        "search_tags": [
            "cerave",
            "moisturizer",
            "face cream",
            "skincare",
            "cerave lotion",
            "dry skin",
            "hydrating cream",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "40",
        "title": "Sunscreen SPF50",
        "category": "Beauty",
        "image_url": "https://images.mamaearth.in/catalog/product/1/_/1_188.jpg?format=auto&height=600",
        "brand": "MamaEarth",
        "ratings": 4.5,
        "rating_count": 2503,
        "price": 7575,
        "discounted_price": 5378,
        "discount_percentage": 29,
        "stock": 29,
        "estimated_delivery_time": "6 days",
        "is_featured": false,
        "search_tags": [
            "neutrogena",
            "sunscreen",
            "spf 50",
            "sunblock",
            "uv protection",
            "skincare",
            "neutrogena sunscreen",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "41",
        "title": "Shampoo",
        "category": "Beauty",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiktcgS89ot3brqQMYN6_4bGsXiq3vshCUktHfOiGIog&s=10",
        "brand": "L'Oréal",
        "ratings": 4.7,
        "rating_count": 4739,
        "price": 4546,
        "discounted_price": 3728,
        "discount_percentage": 18,
        "stock": 59,
        "estimated_delivery_time": "6 days",
        "is_featured": false,
        "search_tags": [
            "loreal",
            "shampoo",
            "hair wash",
            "haircare",
            "loreal shampoo",
            "cleanser",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "42",
        "title": "Conditioner",
        "category": "Beauty",
        "image_url": "https://www.lakmesalon.in/cdn/shop/files/ProductCarousel1.1_e09f4078-2433-4aa9-99f0-1ac5ee881d39.jpg?v=1746775595",
        "brand": "De Fabulous",
        "ratings": 4.6,
        "rating_count": 4063,
        "price": 4384,
        "discounted_price": 3946,
        "discount_percentage": 10,
        "stock": 60,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "dove",
            "conditioner",
            "hair conditioner",
            "haircare",
            "dove conditioner",
            "smooth hair",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "43",
        "title": "Perfume",
        "category": "Beauty",
        "image_url": "https://images.unsplash.com/photo-1593487568720-92097fb460fb?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHBlcmZ1bWV8ZW58MHx8MHx8fDA%3D",
        "brand": "Bella Vita",
        "ratings": 4.5,
        "rating_count": 4419,
        "price": 6263,
        "discounted_price": 5762,
        "discount_percentage": 8,
        "stock": 35,
        "estimated_delivery_time": "6 days",
        "is_featured": false,
        "search_tags": [
            "bella vita",
            "perfume",
            "fragrance",
            "scent",
            "cologne",
            "body spray",
            "edp",
            "beauty"
        ]
    },
    {
        "id": "44",
        "title": "Body Lotion",
        "category": "Beauty",
        "image_url": "https://images.mamaearth.in/catalog/product/1/_/1_64.jpg?format=auto&height=600",
        "brand": "Mama Earth",
        "ratings": 4.3,
        "rating_count": 1759,
        "price": 4831,
        "discounted_price": 4541,
        "discount_percentage": 6,
        "stock": 33,
        "estimated_delivery_time": "2 days",
        "is_featured": false,
        "search_tags": [
            "nivea",
            "body lotion",
            "moisturizer",
            "skincare",
            "nivea cream",
            "dry skin cream",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "45",
        "title": "Hair Oil",
        "category": "Beauty",
        "image_url": "http://res.cloudinary.com/bunnur7c/image/upload/v1785072111/poba2ikaoptxsgcpuej3.jpg",
        "brand": "Parachute",
        "ratings": 4.7,
        "rating_count": 2430,
        "price": 3794,
        "discounted_price": 3073,
        "discount_percentage": 19,
        "stock": 47,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "parachute",
            "hair oil",
            "coconut oil",
            "haircare",
            "parachute oil",
            "scalp care",
            "beauty"
        ]
    },
    {
        "id": "46",
        "title": "Face Mask",
        "category": "Beauty",
        "image_url": "https://thefaceshop.in/cdn/shop/files/8806182593833-3.jpg?v=1745236901&width=1500",
        "brand": "Mamaearth",
        "ratings": 4.3,
        "rating_count": 484,
        "price": 2636,
        "discounted_price": 1845,
        "discount_percentage": 30,
        "stock": 34,
        "estimated_delivery_time": "3 days",
        "is_featured": false,
        "search_tags": [
            "mamaearth",
            "face mask",
            "sheet mask",
            "skincare",
            "face pack",
            "glowing skin",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "47",
        "title": "Foundation",
        "category": "Beauty",
        "image_url": "https://www.paccosmetics.com/cdn/shop/files/8904341204313_IMG.main.jpg?v=1760772103&width=1500",
        "brand": "PCA",
        "ratings": 4.7,
        "rating_count": 3831,
        "price": 5576,
        "discounted_price": 4349,
        "discount_percentage": 22,
        "stock": 22,
        "estimated_delivery_time": "5 days",
        "is_featured": false,
        "search_tags": [
            "lakme",
            "foundation",
            "face makeup",
            "liquid foundation",
            "makeup",
            "base makeup",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "48",
        "title": "Eye Liner",
        "category": "Beauty",
        "image_url": "https://www.ajantabottle.com/storage/media/rpos0X1Lm6eIqnN5ivcfBUr3t43pUMkk6fKHrgkd.jpg",
        "brand": "Lakme",
        "ratings": 4.4,
        "rating_count": 985,
        "price": 4942,
        "discounted_price": 4201,
        "discount_percentage": 15,
        "stock": 58,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "lakme",
            "eyeliner",
            "eye liner",
            "kajal",
            "eye makeup",
            "makeup",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "id": "49",
        "title": "Beard Oil",
        "category": "Beauty",
        "image_url": "https://beardo.in/cdn/shop/files/1_d6a6bc74-8c90-4291-aa64-ec37ac034fff.jpg?v=1704354743",
        "brand": "Beardo",
        "ratings": 4.6,
        "rating_count": 3399,
        "price": 4786,
        "discounted_price": 3446,
        "discount_percentage": 28,
        "stock": 56,
        "estimated_delivery_time": "4 days",
        "is_featured": true,
        "search_tags": [
            "beardo",
            "beard oil",
            "mens grooming",
            "beard care",
            "mustache oil",
            "grooming",
            "beauty"
        ]
    },
    {
        "id": "50",
        "title": "Lip Balm",
        "category": "Beauty",
        "image_url": "http://res.cloudinary.com/bunnur7c/image/upload/v1785070189/qndex2fysclgozbsnzqm.webp",
        "brand": "Nivea",
        "ratings": 4.5,
        "rating_count": 1768,
        "price": 6940,
        "discounted_price": 6593,
        "discount_percentage": 5,
        "stock": 26,
        "estimated_delivery_time": "7 days",
        "is_featured": false,
        "search_tags": [
            "nivea",
            "lip balm",
            "lip care",
            "chapped lips",
            "moisturizer",
            "nivea lip balm",
            "beauty",
            "cosmetics"
        ]
    },
    {
        "title": "I Phone 16 Pro",
        "category": "Electronics",
        "image_url": "http://res.cloudinary.com/bunnur7c/image/upload/v1784998276/aviqrhumf5i1qafvfsy1.jpg",
        "brand": "Apple ",
        "ratings": "4.9",
        "rating_count": "11648",
        "price": 86000,
        "discounted_price": 75000,
        "discount_percentage": 13,
        "stock": "400",
        "estimated_delivery_time": "3 Days",
        "is_featured": false,
        "search_tags": [
            "i phone",
            "apple",
            "ios",
            "mobile phone",
            "iphone 16 pro",
            "flagship phone",
            "electronics",
            "smartphone"
        ],
        "id": "51"
    }
]